module.exports = {
    POLIZAS: 'POLIZAS22',
    CUENTAS: 'CUENTAS15',
    DEPARTAMENTOS: 'DEPTOS',
    FOLIOS:'FOLIOS',
    PERIODOS:'ADMPER',
    AUXILIARES:'AUXILIAR22',
    POLIZA_TIPOS: 'TIPOSPOL',
    LIMIT: "FIRST 100"
}